AWSTemplateFormatVersion: "2010-09-09"
Description: ECS service setup for running it on a cluster using application load balancer

Parameters:
  ProjectName:
    Type: String
    Default: "ops"
    Description: "A friendly environment name that will be used for name spacing all cluster resources. Example: staging, qa, or production"
    AllowedValues: ["ops"]

  ServiceName:
    Description: The name of the service to be created
    Type: String
    Default: sonarqube

  ContainerPort:
    Description: What port number the application inside the docker container is binding to
    Type: Number
    Default: 8080

  ContainerCpu:
    Type: Number
    Default: 128
    Description: How much CPU to give the container. 1024 is 1 CPU

  ContainerMemory:
    Type: Number
    Default: 128
    Description: How much memory in megabytes to give the container

  RevisionNumber:
    Type: String
    Default: latest
    Description: Git commit slug used as a container tag

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${ServiceName}"
      RetentionInDays: 1

  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: !Sub "${ServiceName}"
      NamespaceId:
        Fn::ImportValue: !Sub "${ProjectName}:NamespaceID"
      DnsConfig:
        RoutingPolicy: "MULTIVALUE"
        DnsRecords:
          - Type: "SRV"
            TTL: "60"
      HealthCheckCustomConfig:
        FailureThreshold: "1"

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      UnhealthyThresholdCount: 3
      Name: !Sub "${ServiceName}"
      Port: !Ref "ContainerPort"
      Protocol: TCP
      TargetType: "instance"
      VpcId:
        Fn::ImportValue: !Sub "${ProjectName}:VpcId"
      Tags:
        - Key: "project"
          Value: !Sub "${ProjectName}"

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Fn::ImportValue: !Sub "${ProjectName}:LoadBalancerARN"
      Protocol: TCP
      Port: !Ref "ContainerPort"
      DefaultActions:
        - TargetGroupArn: !Ref "TargetGroup"
          Type: "forward"
          Order: 1

  IamRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${ProjectName}-${ServiceName}-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"

      Description: !Sub "Role for TaskDefinition ${ProjectName}-${ServiceName}"
      MaxSessionDuration: 3600
      Path: /
      Tags:
        - Key: service
          Value: !Sub "${ProjectName}-${ServiceName}"

  IamPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub "${ProjectName}-${ServiceName}-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "cloudwatch:DescribeAlarmsForMetric"
              - "cloudwatch:DescribeAlarmHistory"
              - "cloudwatch:DescribeAlarms"
              - "cloudwatch:ListMetrics"
              - "cloudwatch:GetMetricStatistics"
              - "cloudwatch:GetMetricData"
              - "cloudwatch:GetInsightRuleReport"
              - "logs:DescribeLogGroups"
              - "logs:GetLogGroupFields"
              - "logs:StartQuery"
              - "logs:StopQuery"
              - "logs:GetQueryResults"
              - "logs:GetLogEvents"
              - "ec2:DescribeTags"
              - "ec2:DescribeInstances"
              - "ec2:DescribeRegions"
              - "ecs:Describe*"
              - "ecs:List*"
              - "tag:GetResources"
              - "sqs:GetQueueAttributes"
              - "sqs:GetQueueUrl"
              - "sqs:ListDeadLetterSourceQueues"
              - "sqs:ListQueues"
              - "s3:Get*"
              - "s3:List*"
              - "s3-object-lambda:Get*"
              - "s3-object-lambda:List*"
              - "guardduty:Describe*"
              - "guardduty:Get*"
              - "guardduty:List*"
            Resource: "*"
      Roles:
        - !Ref IamRole

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ServiceName}"
      RequiresCompatibilities:
        - EC2
      TaskRoleArn: !GetAtt [IamRole, Arn]
      ExecutionRoleArn:
        Fn::ImportValue: !Sub "${ProjectName}:EC2Role"
      ContainerDefinitions:
        - Name: !Sub "${ServiceName}"
          Cpu: !Ref "ContainerCpu"
          MemoryReservation: !Ref "ContainerMemory"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ServiceName}:${RevisionNumber}"
          Privileged: false
          ReadonlyRootFilesystem: true
          User: "root"
          DockerSecurityOptions:
            - "apparmor:docker-default"
          MountPoints:
            - ContainerPath: "/var/lib/grafana"
              SourceVolume: "grafana_data"
            - ContainerPath: "/tmp"
              SourceVolume: "grafana_data"
          PortMappings:
            - ContainerPort: !Ref "ContainerPort"
              HostPort: "0"
              Protocol: "tcp"
          Environment:
            - Name: "GF_PLUGINS_PLUGIN_ADMIN_ENABLED"
              Value: "true"
            - Name: "GF_SERVER_SERVE_FROM_SUB_PATH"
              Value: "false"
            - Name: "GF_SERVER_HTTP_PORT"
              Value: !Ref "ContainerPort"
            - Name: "GF_SERVER_DOMAIN"
              Value: "dashboards.ks.net"
            - Name: "GF_SERVER_ROOT_URL"
              Value: "https://dashboards.ks.net"
            - Name: "GF_AUTH_GOOGLE_ENABLED"
              Value: "true"
            - Name: "GF_AUTH_GOOGLE_CLIENT_ID"
              Value: "client_id"
            - Name: "GF_AUTH_GOOGLE_CLIENT_SECRET"
              Value: "add_secret"
            - Name: "GF_AUTH_GOOGLE_SCOPES"
              Value: "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
            - Name: "GF_AUTH_GOOGLE_AUTH_URL"
              Value: "https://accounts.google.com/o/oauth2/auth"
            - Name: "GF_AUTH_GOOGLE_TOKEN_URL"
              Value: "https://accounts.google.com/o/oauth2/token"
            - Name: "GF_AUTH_GOOGLE_ALLOWED_DOMAINS"
              Value: "ks.com"
            - Name: "GF_AUTH_GOOGLE_SIGN_UP"
              Value: "true"  
            - Name: "GF_DATE_FORMATS_FULL_DATE"
              Value: "MMM Do YYYY, hh:mm a"
            - Name: "GF_DATE_FORMATS_INTERVAL_HOUR"
              Value: "MMM Do, HH:mm a"
            - Name: "GF_DATE_FORMATS_INTERVAL_DAY"
              Value: "MMM Do, ddd"
            - Name: "GF_SECURITY_ALLOW_EMBEDDING"
              Value: "true"
            - Name: "GF_ANALYTICS_REPORTING_ENABLED"
              Value: "true"
            - Name: "GF_ANALYTICS_GOOGLE_ANALYTICS_UA_ID"
              Value: "G-25009325"
            - Name: "GF_DATABASE_TYPE"
              Value: "mysql"
            - Name: "GF_DATABASE_HOST"
              Value: "ops-grafana-rds.cq7ho6t400tr.ap-south-1.rds.amazonaws.com"
            - Name: "GF_DATABASE_NAME"
              Value: "grafana"
            - Name: "GF_DATABASE_USER"
              Value: "grafana"
            - Name: "GF_DATABASE_PASSWORD"
              Value: "iRFmWmPbmgpj9Klo0qDv"
          LogConfiguration:
              LogDriver: "awslogs"
              Options:
                awslogs-group: !Ref LogGroup
                awslogs-region: !Ref "AWS::Region"
                awslogs-stream-prefix: "grafana"
      Volumes:
        - Name: "grafana_data"
          EFSVolumeConfiguration:
            FilesystemId:
              Fn::ImportValue: !Sub "${ProjectName}-grafana:FileSystemId"
            TransitEncryption: ENABLED

  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - ServiceDiscovery
      - TaskDefinition
      - TargetGroup
    Properties:
      ServiceName: !Ref "ServiceName"
      Cluster: !Sub "${ProjectName}-cluster"
      LaunchType: "EC2"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: "1"
      TaskDefinition: !Ref "TaskDefinition"
      PropagateTags: TASK_DEFINITION
      LoadBalancers:
        - ContainerName: !Sub "${ServiceName}"
          ContainerPort: !Ref "ContainerPort"
          TargetGroupArn: !Ref "TargetGroup"
      ServiceRegistries:
        - RegistryArn: !GetAtt "ServiceDiscovery.Arn"
          ContainerName: !Sub "${ServiceName}"
          ContainerPort: !Ref "ContainerPort"
